### ISSUE TITLE
factory_girl gem is deprecated

### ISSUE THREAD

**Issue by Lindsay-c-Dennis** [learn-co-curriculum/rails-hello-world-lab#10]
This gem should probably be updated. I had to use bundle exec to run rspec locally, and when I did, I got this deprecation warning message:

DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions.

**Comment by cjbrock** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
issue #9. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
