### ISSUE TITLE
Issue with instructions

### ISSUE THREAD

**Issue by rogercodes1** [learn-co-curriculum/rails-hello-world-lab#12]
### Current: 
Create a **_static controller_** that inherits from the application controller and contains the hello_world action. You can have the call to the view file occur using either the implicit or explicit processes.
**Create a file in the views directory that will be called by the static controller's hello_world action,** and add the heading Hello World to the file. The test is case sensitive, so make sure you enter it exactly as shown.

### update 
**Create a StaticController** that inherits from the application controller and contains the hello_world action. You can have the call to the view file occur using either the implicit or explicit processes.
**Create a static folder within the views directory. Within that folder you will create a file that will be called by the static controller's hello_world action,** and add the heading Hello World to the file. The test is case sensitive, so make sure you enter it exactly as shown.

**Comment by cjbrock** [comment]
Thank you for the feedback on the curriculum @rogercodes1! We'll take the copyedit into consideration in our upcoming revisions of the Rails section. 
// Corinna
