### ISSUE TITLE
bundler issue

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/rails-hello-world-lab#15]
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2) was resolved to 4.2.11, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails
(~> 4.2)', in any of the sources.

**Comment by JoeQuattrone** [comment]
solution install rails 5.0

**Comment by aaj3f** [comment]
Yes, I had the same issue. I just resolved it by removing the constraints on the rails version, changing `gem 'rails', '~> 4.2'` to `gem 'rails'`

**Comment by RachelWyatt** [comment]
I had the same issue but was not able to resolve it by removing the rails version.

**Comment by jenmyers** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
