### ISSUE TITLE
The Desired Solution is Very Specific

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-hello-world-lab#21]
Hey there,

I just wanted to say that the passing solution requires a specific file system set up and the test will not pass unless those specifics are met. For example, if you don't have a folder named hw in your view folder views/hw/hello_world.html.erb the test will not pass. Seems a bit arbitrary if the page renders correctly. If you want the files that specific way, it may be helpful to include directions or build the folders in there prior to the user forking/cloning the lab.

Best,
A

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
